<div class="connect_Links_Area">
    <ul class="connnect_Links_Area_List">
        <li class="title">RUDSAK</li>
        <li class="items"><a>ABOUT US</a></li>
        <li class="items"><a>STORE LOCATOR</a></li>
        <li class="items"><a>GIFT CARDS</a></li>
        <li class="items"><a>CAREER</a></li>
        <li class="items"><a>WHOLESALES</a></li>
        <li class="items"><a>PRESS INQUIRIES</a></li>
        <li class="items"><a>CORPORATE GIFTINGS</a></li>
    </ul>
</div>