<div class="customer_Service_Area">
    <ul class="customer_Service_Area_List">
        <li class="title">CUSTOMER SERVICE</li>
        <li class="items"><a>FAQ</a></li>
        <li class="items"><a>ORDER STATUS</a></li>
        <li class="items"><a>SHIPPING INFORMATION</a></li>
        <li class="items"><a>RETURN & EXCHANGES</a></li>
        <li class="items"><a>SIZE CHART</a></li>
        <li class="items"><a>CONTACT US</a></li>
    </ul>
</div>