<div class="MenuDisplay">
    <ul class="MenuList">
        <li class="MenuListItem"><a>WOMEN</a></li>
        <li class="MenuListItem"><a>MEN</a></li>
        <li class="MenuListItem"><a>KIDS</a></li>
        <li class="MenuListItem"><a>SALES</a></li>
        <li class="MenuListItem" id="search"><a><img id = "search_image" src="<?php echo $this->getViewFileUrl('images/search.svg');?>" /></a>
    </li>
    </ul>
</div>