<link rel="stylesheet" type="text/css" href="<?php echo $block->getViewFileUrl('Magento_Theme::css/owl.carousel.css')?>">
<link rel="stylesheet" type="text/css" href="<?php echo $block->getViewFileUrl('Magento_Theme::css/owl.theme.default.css')?>">
<div id="demo">
 
    <div id="owl-demo" class="owl-carousel owl-theme">
 
        <div class="slide"><img src=”<?php echo $this->getViewFileUrl('images/rudsakImage.png'); ?>”  /></div>
        <div class="slide"><img src=”<?php echo $this->getViewFileUrl('images/rudsakImage1.png'); ?>” /></div>
 
    </div>
 
</div>
<script>
    require([
        'jquery',
        'owlcarousel'
        ], function () {
            'use strict';
            jQuery.noConflict();
                jQuery(".owl-carousel").owlCarousel({
                    items: 1,
                    autoplay: true,
                    dots: false,
                    nav: true,
                    navRewind: true,
                    loop: true
          });
    });
</script>