
<div class="slide"><img src=”<?php echo $this->getViewFileUrl('images/rudsakImage.png'); ?>”  /></div>
<div class="slide"><img src=”<?php echo $this->getViewFileUrl('images/rudsakImage1.png'); ?>” /></div>
 
<!--<div id="demo">
 
    <div id="owl-demo" class="owl-carousel owl-theme">
 
       
    </div>
 
</div>
<script>
    require([
        'jquery',
        'owlcarousel'
        ], function () {
            'use strict';
            jQuery.noConflict();
                jQuery(".owl-carousel").owlCarousel({
                    items: 1,
                    autoplay: true,
                    dots: false,
                    nav: true,
                    navRewind: true,
                    loop: true
          });
    });
</script>-->