<div class = "sliderImage">
        <div class = "slide">
                <img id = "sliderImage1" src="<?php echo $this->getViewFileUrl('images/background.png'); ?>" />
        </div>
        <div class="backward">
                <img id = "backward" src="<?php echo $this->getViewFileUrl('images/backward.png'); ?>" />
        </div>
        <div class="forward">
                <img id = "forward" src="<?php echo $this->getViewFileUrl('images/forward.png'); ?>" />
        </div>
<div>

