<div class="social_Links_Area">
    <ul class="social_Links_Area_List">
        <li class="title">CONNECT WITH US</li>
        <li class="items" id="facebook"><a><img class="logo" src="<?php echo $this->getViewFileUrl('images/facebook.png'); ?>" /></a></li>
        <li class="items" id="twitter"><a><img class="logo" src="<?php echo $this->getViewFileUrl('images/twitter.png'); ?>" /></a></li>
        <li class="items" id="insta"><a><img class="logo" src="<?php echo $this->getViewFileUrl('images/insta.png'); ?>" /></a></li>
        <li class="items" id="youtube"><a><img class="logo" src="<?php echo $this->getViewFileUrl('images/youtube.png'); ?>" /></a></li>
        <li class="items" id="pintrest"><a><img class="logo" src="<?php echo $this->getViewFileUrl('images/pintrest.png'); ?>" /></a></li>
    </ul>
</div>