<div class = "menu">
    <ul class = "categories_list">
        <li class = "women"><a href = ""><?php echo _("Women"); ?></a></li>
        <li class = "men"><a href = ""><?php echo _("Men"); ?></a></li>
        <li class =  "kids"><a href = ""><?php echo _("Kids"); ?></a></li>
        <li class = "sales"><a href = ""><?php echo _("Sales"); ?></a></li>
        <li class = "search"><a href = "" class = "searchLink"><img src="<?php echo $this->getViewFileUrl('images/search.svg'); ?>" /></a>
            <ul id = "form">
                <li id = "search_bar"><input type = "text" id = "search_bar" placeholder = "What are you looking for" /></li>
                <li id = "submit"><input type = "submit" id = "button " value = "SEARCH" /></li>
            </ul>
        </li>
    </ul>   
</div>