<ul class = "categories_list">
    <li class = "women"><a href = ""><?php echo _("Women"); ?></a></li>
    <li class = "men"><a href = ""><?php echo _("Men"); ?></a></li>
    <li class =  "kids"><a href = ""><?php echo _("Kids"); ?></a></li>
    <li class = "sales"><a href = ""><?php echo _("Sales"); ?></a></li>
    <li class = "search"><a href = ""><img src="<?php echo $this->getViewFileUrl('images/search.svg'); ?>" /></a></li>
</ul>
<form action "">
    <input type = "text" paceholder = "What are you looking for">
    <input type = "submit" value = "SEARCH">
</form>