<div id = "wSecond_Slider">
    <div id = "slider">
        <div class = "image">
            <img id = "image3" src="<?php echo $this->getViewFileUrl('images/image3.png'); ?>" />
        </div>
        <div class = "image">
            <<img id = "image4" src="<?php echo $this->getViewFileUrl('images/image4.png'); ?>" />
        </div>
    </div>
    <div id="naivigation">
        <div id ="nav3">
            <img id = "button3" src="<?php echo $this->getViewFileUrl('images/button3.png'); ?>" />
        </div>
        <div id ="nav4">
            <img id = "button4" src="<?php echo $this->getViewFileUrl('images/button4.png'); ?>" />
        </div>
    </div>
</div>